# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Over the Horizon
tagline:             Random thoughts, rants and surprise easter eggs 
url:                 
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Zu Ming Tan
  url:               
  email:             zooming.tan@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/zooming-tan/zooming-tan.github.io
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
